spring:
      datasource:
        driver-class-name:  com.mysql.cj.jdbc.Driver
        url:   jdbc:mysql://123.207.172.223:3306/car?useUnicode=true&characterEncoding=utf8
        username:  team
        password:  teampass
        type: org.apache.commons.dbcp2.BasicDataSource
        dbcp2:
          max-wait-millis:  5000
          min-idle:  5
          initial-size: 5
          connection-properties: characterEncoding=utf8
          max-total:  10
      redis:
        host: v4bug.com
        password: teampass
hello:
      myname: bwy
mybatis:
        type-aliases-package: cn.saytime.bean

file:
  image-path: c:/temp/image
  max-file-size: 5242880 #5MB
  server-port: 6435
  server-host: localhost

project:
  controller:
    allowed:
      origins: http://car.v4bug.com
      methods: GET, POST, PUT, DELETE, OPTIONS
    domain: http://car.v4bug.com #后端域名
    verify:
      interval: 1000
      width: 100
      height: 30
      number: 4

emailServer:
    serverhost: smtp.wmgblog.shop
    user: hanshuocar@wmgblog.shop
    password: hs12345678+

